project_name: django-project-template-py3   ### CHANGE ME ###
server_git_url: https://github.com/magnet-cl/django-project-template-py3.git   ### CHANGE ME ###
server_root_dir: /home/{{ ansible_user }}/{{ project_name }}
service_name: django-{{ project_name }}.service
development: no
django_port: 8000
ansible_python_interpreter: auto
