dependency:
  name: galaxy
  options:
    role-file: requirements.yaml    # relative to base https://github.com/ansible/molecule/issues/1509

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint  # TODO: configure

platforms:
  - name: instance
    box: ubuntu/bionic64
    memory: 1024 # MB

provisioner:
  name: ansible

  config_options:
    defaults:
      stdout_callback: debug    # human-readable output

  playbooks:
    converge: ../../playbooks/deploy.yaml

  inventory:
    #   host_vars:
    #     instance:
    # doesn't work together with `links`
    links:
      group_vars: ../../group_vars/
      host_vars: host_vars/

  lint:
    name: ansible-lint  # TODO: configure
    enabled: no   # TODO

verifier:
  name: testinfra
  lint:
    name: flake8

scenario:
  create_sequence:
    # - dependency    speedup
    - create
    - prepare
  check_sequence:
    # - dependency    speedup
    # - cleanup       not configured
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    # - dependency    speedup
    - create
    - prepare
    - converge
  destroy_sequence:
    # - dependency    speedup
    # - cleanup       not configured
    - destroy
  test_sequence:
    - lint
    - dependency
    # - cleanup       not configured
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect   not configured
    - verify
    # - cleanup       not configured
    - destroy
