- name: Prepare
  hosts: all
  gather_facts: false

  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      become: true
      changed_when: false

    - name: set english environment locale
      lineinfile:
        path: /etc/environment
        regexp: ^LC_ALL=
        line: LC_ALL=en_US.UTF-8
      become: yes

    # However, as Ansible reuses the SSH connection,
    # the converge playbook still uses the old environment.

    # - meta: reset_connection    -- didn't work
    # Setting some variations of ssh_args with ControlMaster also didn't work.
    # This is very _cuma_ but works!:
    # https://stackoverflow.com/questions/26677064/create-and-use-group-without-restart/37337848#37337848
    - name: Reconnect SSH
      shell: sleep 1; pkill -u {{ ansible_ssh_user }} sshd
      async: 3
      poll: 2
      # `when` is unnecessary because instances are prepared only once.
      changed_when: true  # Silence linter
